services:
  gateway:
    build:
      context: ./src/gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=7659
    - OUTPUT_QUEUE=raw_data_queue
    - INPUT_QUEUE_0=results_0
    - INPUT_QUEUE_1=results_1
    - INPUT_QUEUE_2=results_2
    - INPUT_QUEUE_3=results_3
    - INPUT_QUEUE_4=results_4
  q1_data_reducer_0:
    build:
      context: ./src/data_cleaner
      dockerfile: Dockerfile
    container_name: q1_data_reducer_0
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - INPUT_EXCHANGE=usd_transactions_exc
    - N_UPSTREAM=1
    - SHARD_ID=0
    - OUTPUT_QUEUE=q1_reduced_data
    - KEEP_COLUMNS=From Bank,Account,To Bank,Account.1,Amount Paid
  q1_filter_lt_50_usd_0:
    build:
      context: ./src/filter
      dockerfile: Dockerfile
    container_name: q1_filter_lt_50_usd_0
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - INPUT_QUEUE=q1_reduced_data
    - OUTPUT_QUEUE=results_1
    - FILTER_FIELD=Amount Paid
    - FILTER_OP=50
    - FILTER_VALUE=lt
  usd_filter_0:
    build:
      context: ./src/filter
      dockerfile: Dockerfile
    container_name: usd_filter_0
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - INPUT_QUEUE=cleanded_data_queue
    - OUTPUT_EXCHANGE=usd_transactions_exc
    - FILTER_FIELD=Payment Currency
    - FILTER_OP=eq
    - FILTER_VALUE=US Dollar
