services:
  client_0:
    build:
      context: ./src
      dockerfile: client/Dockerfile
    container_name: client_0
    depends_on:
      gateway:
        condition: service_started
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=7659
    - BATCH_SIZE=500
    - TRANSACTIONS_FILE=/datasets/transactions_10k.csv
    - ACCOUNTS_FILE=/datasets/accounts_10k.csv
    - CLIENT_ID=0
    - RESULTS_DIR=/results
    volumes:
    - ./datasets:/datasets
    - ./results:/results
  gateway:
    build:
      context: ./src
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=7659
    - OUTPUT_EXCHANGE=gateway_exc
    - INPUT_QUEUE_PREFIX=results
    - TOTAL_QUERIES=3
    - OUTPUT_SHARDS=2
    - QUERY_1_N_UPSTREAM=2
    - QUERY_2_N_UPSTREAM=2
    - QUERY_3_N_UPSTREAM=1
    - TRANSACTION_COLUMNS=Timestamp,From Bank,Account,To Bank,Account.1,Amount Received,Receiving
      Currency,Amount Paid,Payment Currency,Payment Format
  q1_data_reducer_0:
    build:
      context: ./src
      dockerfile: data_reducer/Dockerfile
    container_name: q1_data_reducer_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=2
    - INPUT_EXCHANGE=usd_transactions_exc
    - SHARD_ID=0
    - OUTPUT_EXCHANGE=q1_reduced_exc
    - OUTPUT_SHARDS=2
    - KEEP_COLUMNS=From Bank,Account,To Bank,Account.1,Amount Paid
    - TOTAL_CLIENTS=1
  q1_data_reducer_1:
    build:
      context: ./src
      dockerfile: data_reducer/Dockerfile
    container_name: q1_data_reducer_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=2
    - INPUT_EXCHANGE=usd_transactions_exc
    - SHARD_ID=1
    - OUTPUT_EXCHANGE=q1_reduced_exc
    - OUTPUT_SHARDS=2
    - KEEP_COLUMNS=From Bank,Account,To Bank,Account.1,Amount Paid
    - TOTAL_CLIENTS=1
  q1_data_reducer_2:
    build:
      context: ./src
      dockerfile: data_reducer/Dockerfile
    container_name: q1_data_reducer_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=2
    - INPUT_EXCHANGE=usd_transactions_exc
    - SHARD_ID=2
    - OUTPUT_EXCHANGE=q1_reduced_exc
    - OUTPUT_SHARDS=2
    - KEEP_COLUMNS=From Bank,Account,To Bank,Account.1,Amount Paid
    - TOTAL_CLIENTS=1
  q1_filter_lt_50_0:
    build:
      context: ./src
      dockerfile: filters/Dockerfile
    container_name: q1_filter_lt_50_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - N_UPSTREAM=3
    - INPUT_EXCHANGE=q1_reduced_exc
    - SHARD_ID=0
    - OUTPUT_QUEUE=results_1
    - FILTER_FIELD=Amount Paid
    - FILTER_OP=lt
    - FILTER_VALUE=50
    - TOTAL_CLIENTS=1
  q1_filter_lt_50_1:
    build:
      context: ./src
      dockerfile: filters/Dockerfile
    container_name: q1_filter_lt_50_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - N_UPSTREAM=3
    - INPUT_EXCHANGE=q1_reduced_exc
    - SHARD_ID=1
    - OUTPUT_QUEUE=results_1
    - FILTER_FIELD=Amount Paid
    - FILTER_OP=lt
    - FILTER_VALUE=50
    - TOTAL_CLIENTS=1
  q2_aggregator_0:
    build:
      context: ./src
      dockerfile: aggregators/Dockerfile
    container_name: q2_aggregator_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - INPUT_EXCHANGE=q2_reduced_exc
    - SHARD_ID=0
    - N_UPSTREAM=2
    - OUTPUT_QUEUE=results_2
    - AGG_OP=max
    - AGG_FIELD=Amount Paid
    - KEY_FIELD=From Bank
    - CARRY_FIELDS=Account
    - TOTAL_CLIENTS=1
  q2_aggregator_1:
    build:
      context: ./src
      dockerfile: aggregators/Dockerfile
    container_name: q2_aggregator_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - INPUT_EXCHANGE=q2_reduced_exc
    - SHARD_ID=1
    - N_UPSTREAM=2
    - OUTPUT_QUEUE=results_2
    - AGG_OP=max
    - AGG_FIELD=Amount Paid
    - KEY_FIELD=From Bank
    - CARRY_FIELDS=Account
    - TOTAL_CLIENTS=1
  q2_data_reducer_0:
    build:
      context: ./src
      dockerfile: data_reducer/Dockerfile
    container_name: q2_data_reducer_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=3
    - INPUT_EXCHANGE=q2_by_bank_exc
    - SHARD_ID=0
    - OUTPUT_EXCHANGE=q2_reduced_exc
    - OUTPUT_SHARDS=2
    - KEEP_COLUMNS=From Bank,Account,Amount Paid
    - TOTAL_CLIENTS=1
    - ROUTING_FIELD=From Bank
  q2_data_reducer_1:
    build:
      context: ./src
      dockerfile: data_reducer/Dockerfile
    container_name: q2_data_reducer_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=3
    - INPUT_EXCHANGE=q2_by_bank_exc
    - SHARD_ID=1
    - OUTPUT_EXCHANGE=q2_reduced_exc
    - OUTPUT_SHARDS=2
    - KEEP_COLUMNS=From Bank,Account,Amount Paid
    - TOTAL_CLIENTS=1
    - ROUTING_FIELD=From Bank
  q2_splitter_by_bank_0:
    build:
      context: ./src
      dockerfile: aggregators/Dockerfile
    container_name: q2_splitter_by_bank_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint:
    - python3
    - /app/splitter.py
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - INPUT_EXCHANGE=usd_transactions_exc
    - SHARD_ID=0
    - OUTPUT_EXCHANGE=q2_by_bank_exc
    - N_UPSTREAM=2
    - OUTPUT_SHARDS=2
    - SHARD_KEY_FIELD=From Bank
    - TOTAL_CLIENTS=1
  q2_splitter_by_bank_1:
    build:
      context: ./src
      dockerfile: aggregators/Dockerfile
    container_name: q2_splitter_by_bank_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint:
    - python3
    - /app/splitter.py
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - INPUT_EXCHANGE=usd_transactions_exc
    - SHARD_ID=1
    - OUTPUT_EXCHANGE=q2_by_bank_exc
    - N_UPSTREAM=2
    - OUTPUT_SHARDS=2
    - SHARD_KEY_FIELD=From Bank
    - TOTAL_CLIENTS=1
  q2_splitter_by_bank_2:
    build:
      context: ./src
      dockerfile: aggregators/Dockerfile
    container_name: q2_splitter_by_bank_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint:
    - python3
    - /app/splitter.py
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - INPUT_EXCHANGE=usd_transactions_exc
    - SHARD_ID=2
    - OUTPUT_EXCHANGE=q2_by_bank_exc
    - N_UPSTREAM=2
    - OUTPUT_SHARDS=2
    - SHARD_KEY_FIELD=From Bank
    - TOTAL_CLIENTS=1
  q5_counter_0:
    build:
      context: ./src
      dockerfile: aggregators/Dockerfile
    container_name: q5_counter_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - INPUT_QUEUE=q5_countable_transactions
    - OUTPUT_QUEUE=q5_totals_reached
    - AGG_OP=count
  q5_data_reducer_0:
    build:
      context: ./src
      dockerfile: data_reducer/Dockerfile
    container_name: q5_data_reducer_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - INPUT_EXCHANGE=gateway_exc
    - SHARD_ID=0
    - OUTPUT_QUEUE=q5_reduced_data
    - KEEP_COLUMNS=Timestamp,Amount Paid,Payment Currency,Payment Format
  q5_data_reducer_1:
    build:
      context: ./src
      dockerfile: data_reducer/Dockerfile
    container_name: q5_data_reducer_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - INPUT_EXCHANGE=gateway_exc
    - SHARD_ID=1
    - OUTPUT_QUEUE=q5_reduced_data
    - KEEP_COLUMNS=Timestamp,Amount Paid,Payment Currency,Payment Format
  q5_data_reducer_2:
    build:
      context: ./src
      dockerfile: data_reducer/Dockerfile
    container_name: q5_data_reducer_2
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - INPUT_EXCHANGE=gateway_exc
    - SHARD_ID=2
    - OUTPUT_QUEUE=q5_reduced_data
    - KEEP_COLUMNS=Timestamp,Amount Paid,Payment Currency,Payment Format
  q5_filter_01092022_05092022_0:
    build:
      context: ./src
      dockerfile: filters/Dockerfile
    container_name: q5_filter_01092022_05092022_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - N_UPSTREAM=1
    - INPUT_QUEUE=q5_reduced_data
    - OUTPUT_QUEUE=q5_converter_to_usd
    - FILTER_FIELD=Timestamp
    - FILTER_OP=in
    - FILTER_VALUE=["2022/09/01", "2022/09/05"]
  q5_filter_lt_1_usd_0:
    build:
      context: ./src
      dockerfile: filters/Dockerfile
    container_name: q5_filter_lt_1_usd_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - N_UPSTREAM=1
    - INPUT_QUEUE=q5_converted_amounts_transactions
    - OUTPUT_QUEUE=q5_small_amounts_transactions
    - FILTER_FIELD=Amount Paid
    - FILTER_OP=lt
    - FILTER_VALUE=1
  q5_money_converter_0:
    build:
      context: ./src
      dockerfile: money_converter/Dockerfile
    container_name: q5_money_converter_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - OP_MODE=PIPELINE
    - MAIN_INPUT_QUEUE=q5_converter_to_usd
    - SECONDARY_INPUT_QUEUE=q5_currency_rates_from_api
    - MAIN_OUTPUT_QUEUE=q5_reqs_currency_rates_api
    - SECONDARY_OUTPUT_QUEUE=q5_converted_amounts_transactions
    - TARGET_CURRENCY=US Dollar
    - BATCH_SIZE=1
  q5_money_converter_api_client_0:
    build:
      context: ./src
      dockerfile: money_converter/Dockerfile
    container_name: q5_money_converter_api_client_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint:
    - python3
    - money_converter_api.py
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - N_UPSTREAM=1
    - INPUT_QUEUE=q5_reqs_currency_rates_api
    - OUTPUT_QUEUE=q5_currency_rates_from_api
  q5_payment_fmt_filter_0:
    build:
      context: ./src
      dockerfile: filters/Dockerfile
    container_name: q5_payment_fmt_filter_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - N_UPSTREAM=1
    - INPUT_QUEUE=q5_small_amounts_transactions
    - OUTPUT_QUEUE=q5_countable_transactions
    - FILTER_FIELD=Payment Format
    - FILTER_OP=in
    - FILTER_VALUE=["Wire", "ACH"]
  q5_transaction_counter_0:
    build:
      context: ./src
      dockerfile: aggregators/Dockerfile
    container_name: q5_transaction_counter_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
    - INPUT_QUEUE=q5_totals_reached
    - OUTPUT_QUEUE=results_3
    - AGG_OP=sum
    - AGG_FIELD=count
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=warning
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  usd_filter_0:
    build:
      context: ./src
      dockerfile: filters/Dockerfile
    container_name: usd_filter_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - N_UPSTREAM=1
    - INPUT_EXCHANGE=gateway_exc
    - SHARD_ID=0
    - OUTPUT_EXCHANGE=usd_transactions_exc
    - OUTPUT_SHARDS=3
    - FILTER_FIELD=Payment Currency
    - FILTER_OP=eq
    - FILTER_VALUE=US Dollar
    - TOTAL_CLIENTS=1
  usd_filter_1:
    build:
      context: ./src
      dockerfile: filters/Dockerfile
    container_name: usd_filter_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - RABBITMQ_HOST=rabbitmq
    - N_UPSTREAM=1
    - N_UPSTREAM=1
    - INPUT_EXCHANGE=gateway_exc
    - SHARD_ID=1
    - OUTPUT_EXCHANGE=usd_transactions_exc
    - OUTPUT_SHARDS=3
    - FILTER_FIELD=Payment Currency
    - FILTER_OP=eq
    - FILTER_VALUE=US Dollar
    - TOTAL_CLIENTS=1
