build:
  context: ./src
  dockerfile: barrier_filter/Dockerfile
container_name: barrier_filter
depends_on:
  rabbitmq:
    condition: service_healthy
environment:
- MOM_HOST=rabbitmq
- PYTHONUNBUFFERED=1
- OP_MODE=JOINER
- COEF=0.01
volumes:
- ./worker_logs:/worker_logs