rabbitmq:
  build:
    context: ./src/rabbitmq
    dockerfile: Dockerfile
  container_name: rabbitmq
  environment:
  - RABBITMQ_LOG_LEVELS=warning
  healthcheck:
    interval: 5s
    retries: 10
    start_period: 50s
    test: rabbitmq-diagnostics check_port_connectivity
    timeout: 3s
  ports:
  - 5672:5672
  - 15672:15672