build:
  context: ./src
  dockerfile: graph_edges_filter/Dockerfile
depends_on:
  rabbitmq:
    condition: service_healthy
entrypoint:
- python3
- incoming_edges_filter.py
environment:
- MOM_HOST=rabbitmq
- PYTHONUNBUFFERED=1
volumes:
- ./worker_logs:/worker_logs