build:
  context: ./src
  dockerfile: graph_paths/Dockerfile
depends_on:
  rabbitmq:
    condition: service_healthy
entrypoint:
- python3
- paths_aggregator.py
environment:
- MOM_HOST=rabbitmq
- PYTHONUNBUFFERED=1
volumes:
- ./worker_logs:/worker_logs