build:
  context: ./src
  dockerfile: filters/Dockerfile
depends_on:
  rabbitmq:
    condition: service_healthy
environment:
- RABBITMQ_HOST=rabbitmq
- BATCH_SIZE=5000
volumes:
- ./worker_logs:/worker_logs